# Generated by Django 5.0.2 on 2024-02-12 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.CharField(max_length=100)),
                ('humedad', models.CharField(max_length=50)),
                ('velocidad_viento', models.PositiveSmallIntegerField()),
                ('ciudad', models.CharField(max_length=50)),
                ('fecha', models.CharField(max_length=50)),
            ],
        ),
    ]
