# Generated by Django 5.0.2 on 2024-02-12 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clima',
            name='velocidad_viento',
            field=models.FloatField(),
        ),
    ]
