# Generated by Django 5.0.2 on 2024-02-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0002_alter_clima_velocidad_viento'),
    ]

    operations = [
        migrations.AddField(
            model_name='clima',
            name='key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
